!
! Zebra configuration saved from vty
!   2026/06/04 03:44:01
!
frr version 8.4_git
frr defaults traditional
!
hostname leaf4
!
!
!
!
!
interface eth1
 ip address 10.0.0.7/31
exit
!
interface eth2
 ip address 10.0.0.15/31
exit
!
interface eth3
 ip address 192.168.4.1/24
exit
!
!
interface lo
 ip address 10.255.1.4/32
exit
!
!
!
no ipv6 forwarding
!
!
!
!
!
