---
- name: Roll back DNS servers on spine switches
  hosts: spine_sw
  become: true
  gather_facts: false

  vars:
    dns:
      vrf: mgmt

      current_servers:
        ipv4:
          - "10.0.0.100"
          - "10.0.0.101"

      desired_servers:
        ipv4:
          - "1.1.1.1"
          - "8.8.8.8"

  roles:
    - role: change_dns
      tags:
        - rollback_dns
