hostname spine1
log stdout

ip forwarding

interface lo
 ip address 10.255.0.1/32

interface eth1
 description to leaf1 eth1
 ip address 10.0.0.0/31

interface eth2
 description to leaf2 eth1
 ip address 10.0.0.2/31