hostname leaf3
log stdout

router bgp 65103
 bgp router-id 10.255.1.3
 no bgp ebgp-requires-policy

 neighbor 10.0.0.8 remote-as 65000
 neighbor 10.0.0.8 description spine1 eth3

 neighbor 10.0.0.12 remote-as 65000
 neighbor 10.0.0.12 description spine2 eth3

 address-family ipv4 unicast
  network 10.255.1.3/32
  maximum-paths 2
 exit-address-family
 address-family l2vpn evpn
  neighbor 10.0.0.8 activate
  neighbor 10.0.0.12 activate
  advertise-all-vni
  vni 10020
   route-target import 65000:10020
   route-target export 65000:10020
  exit-vni
 exit-address-family

router bgp 65103 vrf tenant-a
 bgp router-id 10.255.1.3

 address-family ipv4 unicast
  redistribute connected
 exit-address-family

 address-family l2vpn evpn
  advertise ipv4 unicast
 exit-address-family