hostname leaf3
log stdout

ip forwarding

interface lo
 ip address 10.255.1.3/32

interface eth1
 description to spine1 eth3
 ip address 10.0.0.9/31

interface eth2
 description to spine2 eth3
 ip address 10.0.0.13/31

interface eth3
 description to host3 eth1