hostname leaf1
log stdout

ip forwarding

vrf tenant-a
 vni 10099
exit-vrf

interface lo
 ip address 10.255.1.1/32

interface eth1
 description to spine1 eth1
 ip address 10.0.0.1/31

interface eth2
 description to spine2 eth1
 ip address 10.0.0.5/31

interface eth3
 description to host1 eth1