hostname leaf2
log stdout

router bgp 65102
 bgp router-id 10.255.1.2
 no bgp ebgp-requires-policy

 neighbor 10.0.0.2 remote-as 65000
 neighbor 10.0.0.2 description spine1 eth2

 neighbor 10.0.0.6 remote-as 65000
 neighbor 10.0.0.6 description spine2 eth2

 address-family ipv4 unicast
  network 10.255.1.2/32
  maximum-paths 2
 exit-address-family
 address-family l2vpn evpn
  neighbor 10.0.0.2 activate
  neighbor 10.0.0.6 activate
  advertise-all-vni
  vni 10010
   route-target import 65000:10010
   route-target export 65000:10010
  exit-vni
 exit-address-family

router bgp 65102 vrf tenant-a
 bgp router-id 10.255.1.2
 address-family ipv4 unicast
  redistribute connected
 exit-address-family
 address-family l2vpn evpn
  advertise ipv4 unicast
  route-target import 65000:10099
  route-target export 65000:10099
 exit-address-family
