hostname leaf2
log stdout

ip forwarding

vrf tenant-a
 vni 10099
exit-vrf

interface lo
 ip address 10.255.1.2/32

interface eth1
 description to spine1 eth2
 ip address 10.0.0.3/31

interface eth2
 description to spine2 eth2
 ip address 10.0.0.7/31

interface eth3
 description to host2 eth1