hostname leaf4
log stdout

ip forwarding

interface lo
 ip address 10.255.1.4/32

interface eth1
 description to spine1 eth4
 ip address 10.0.0.11/31

interface eth2
 description to spine2 eth4
 ip address 10.0.0.15/31

interface eth3
 description to host4 eth1