---
- name: Inspect VLANs on leaf switches
  hosts: leaf_sw
  gather_facts: false

  roles:
    - role: cumulus_inspect
      vars:
        inspect_command: "show bridge domain br_default vlan"

- name: Inspect interfaces on spine switches
  hosts: spine_sw
  gather_facts: false

  roles:
    - role: cumulus_inspect
      vars:
        inspect_command: "show interface"
